### ISSUE TITLE
some records have somewhere empty. It crashes the process

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE-Migration#1]
It crashed on a handle with somewhere empty:
```
Warning: Handle 842/190fa89e-a8a6-11e5-a711-fa163e62896a contains a PPID entry pointing to a non-existing Handle!
Traceback (most recent call last):
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 290, in <module>
    migration_tool.execute()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 45, in execute
    self.migrate_handles()
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 177, in migrate_handles
    original_record = self.retrieve_handle_record_remotely(predecessor)
  File "/home/handle1/git/B2HANDLE-Migration/b2handle-migration/migrationtool.py", line 86, in retrieve_handle_record_remotely
    return self.b2handleclient.retrieve_handle_record(handle_name)
  File "/usr/lib/python2.6/site-packages/b2handle/handleclient.py", line 319, in retrieve_handle_record
    handlerecord_json = self.__get_handle_record_if_necessary(handle, handlerecord_json)
  File "/usr/lib/python2.6/site-packages/b2handle/handleclient.py", line 1091, in __get_handle_record_if_necessary
    handlerecord_json = self.retrieve_handle_record_json(handle)
  File "/usr/lib/python2.6/site-packages/b2handle/handleclient.py", line 274, in retrieve_handle_record_json
    utilhandle.check_handle_syntax(handle)
  File "/usr/lib/python2.6/site-packages/b2handle/utilhandle.py", line 55, in check_handle_syntax
    raise handleexceptions.HandleSyntaxError(msg=msg, handle=string, expected_syntax=expected)
b2handle.handleexceptions.HandleSyntaxError: Handle empty does not have expected syntax: No slash.
	Expected: prefix/suffix
```

**Comment by TobiasWeigel** [comment]
Fixed in 1c16c4b3b7acdd7bbae47af6153923f178129ff1: Show warning on bad Handle syntax, but continue.
